### ISSUE TITLE
Topology without switches

### ISSUE THREAD

**Issue by v1peractual** [treydock/puppet-slurm#36]
Hello,

We are setting up a dragonfly topology.  I don't seem to be able to get the topology file to populate.
I setup Hiera as the following:

slurm::switch:
  ss01:
    nodes: "cn0[01-32]"
  ss02:
    nodes: "cn0[33-60]"
  ss03:
    nodes: "cn0[61-92]"
  ss04:
    nodes: "cn[093-124]"
  ss05:
    nodes: "gpua0[01-16],gpuc[01-05]"
  ss06:
    nodes: "gpua0[17-44]"
  ss07:
    nodes: "gpua0[45-72]"
  ss08:
    nodes: "gpua[073-100]"
  ss09:
    nodes: "gpub0[01-16],gpud01"
  ss10:
    nodes: "gpub0[17-44]"
  ss11:
    nodes: "gpub0[45-72]"
  ss12:
    nodes: "gpub[072-100]"

I get no errors, but it does nothing. Looking at manifests/switch.pp:

```
  if ! $nodes and ! $switches {
    fail('slurm::switch: Must define either nodes or switches')
  }
```

Should that 'and' be an 'or'? I don't see any failures. Am I missing something?

Thank you for the work on the Puppet module. It it working great.

**Comment by treydock** [comment]
The top level key in Hiera should be `slurm::switches` (plural).  Try that and see if that solves the issue. Usually if you make a change in Hiera and nothing happens, it's often the key is not recognized by a Puppet module.  Also the `and` is correct as the error is basically if both nodes and switches are undefined, it will fail since at least one of those is needed.  If you don't see any failures then that condition isn't getting hit.

**Comment by v1peractual** [comment]
Thanks. I just figured it out before you responded. I appreciate it.
