### ISSUE TITLE
Support for login nodes in treydock/puppet-slurm

### ISSUE THREAD

**Issue by pmekhedjian** [treydock/puppet-slurm#59]
Does treydock/puppet-slurm support Slurm login nodes? I see roles for slurmdbd, slurmctld, slurmd, client, slurmrestd, but not one for login nodes exclusively.
 
Have I overlooked something? Is there a combo of roles I should look at that enable this?

**Comment by treydock** [comment]
The "client" role is intended for login nodes if all the login node needs to do is submit/query/etc jobs.  I use the "slurmd" role on OSC’s login nodes cause they are setup using configless Slurm so they are defined in slurm.conf as nodes with no partition assignment so that when I do "scontrol reconfig" they get latest configs from scheduler.

**Comment by treydock** [comment]
Please re-open and describe if the client and/or slurmd roles don't work in your case.
